const USER_EXISTS_ERROR = "User Already Exists";
const USER_DOES_NOT_EXISTS_ERROR = "USER DOES NOT EXISTS";
const SYSTEM_ERROR = "SYSTEM_ERROR";
const INVALID_PASS_ERROR = "INVALID CREDENTIALS";
const INCOMPLETE_DATA_ERROR = "INCOMPLETE DATA";


module.exports = {
    USER_EXISTS_ERROR, 
    USER_DOES_NOT_EXISTS_ERROR, 
    SYSTEM_ERROR,
    INCOMPLETE_DATA_ERROR,
};